version: "3.8"
services:
  app:
    build:
      context: .
      target: development
    ports:
      - "5000:5000"
    env_file: .env.test
  tests:
    build:
      context: .
      dockerfile: Dockerfile.ci
    env_file: .env.test
